server:
  port: 8083

spring:
  application:
    name: CATEGORY-SERVICE

  mvc:
    pathmatch:
        matching-strategy: ant_path_matcher

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-uri:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost